### ISSUE TITLE
PancakeSwap Websocket Connection does not stay alive; closes after some time

### ISSUE THREAD

**Issue by sadhippo** [Nethereum/Nethereum.WSLogStreamingUniswapSample#1]
Using this example for PancakeSwap: https://github.com/Nethereum/Nethereum.Templates.WebSocketStreaming/blob/master/ExampleLogsUniswapSyncSubscription.cs#L70

After 5-10 minutes, the connection closes and cannot be reconnected to.

Error message: 
Nethereum.JsonRpc.Client.RpcClientUnknownException: Error occurred trying to send web socket requests(s)
---> System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived'
at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
at System.Net.WebSockets.ManagedWebSocket.SendPrivateAsync(ReadOnlyMemory`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
at Nethereum.JsonRpc.WebSocketStreamingClient.StreamingWebSocketClient.SendRequestAsync(RpcRequestMessage request, IRpcStreamingResponseHandler requestResponseHandler, String route)
--- End of inner exception stack trace ---
at Nethereum.JsonRpc.WebSocketStreamingClient.StreamingWebSocketClient.SendRequestAsync(RpcRequestMessage request, IRpcStreamingResponseHandler requestResponseHandler, String route)
at Nethereum.JsonRpc.WebSocketStreamingClient.StreamingWebSocketClient.SendRequestAsync(RpcRequest request, IRpcStreamingResponseHandler requestResponseHandler, String route)

**Comment by yaeszlo** [comment]
I have the same issue. No one able to help?
